yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('', views.index, name='posts_main'),

]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    class Meta:
        ordering = ['-pub_date']

    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )

    def __str__(self):
        return self.text

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render

from .models import Group, Post

RANGE_POSTS = 10


def index(requests):
    posts = Post.objects.all()[:RANGE_POSTS]
    template = 'posts/index.html'
    main_page = "Последние обновления на сайте"
    context = {
        'main_page': main_page,
        'posts': posts,
    }
    return render(requests, template, context)


def group_posts(requests, slug):
    group = get_object_or_404(Group, slug=slug)
    template = 'posts/group_list.html'
    posts = group.posts.all()[:RANGE_POSTS]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(requests, template, context)

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../../../../../Desktop/Яндекс%20практикум/web_hw02_community_with_text/img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../../../../../Desktop/Яндекс%20практикум/web_hw02_community_with_text/img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../../../../../Desktop/Яндекс%20практикум/web_hw02_community_with_text/img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static  'css/bootstrap.min.css' %}">
    <title>{% block title %}Текст заголовка страницы{% endblock %}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main><div class="container py-5">
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
        </div>
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->
    <footer class="border-top text-center py-3">
       {% include 'includes/footer.html' %}
    </footer>
  </body>

yatube/templates/includes/footer.html
 <footer class="border-top text-center py-3">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>
    </footer>

yatube/templates/includes/header.html
{% load static %}
<header>
      <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:posts_main' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube</a>
          </a>
        </div>
      </nav>
    </header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
Записи сообщества {{ group.description }}
{% endblock %}
{% block content %}
    <main>
        <div class="container py-5">
        <h1>{{ group }}</h1>
        <p>
            {{ group.description }}
        </p>
       {% for post in posts %}
    <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>

  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}<!-- под последним постом нет линии -->
      <
    </main>

    {% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
{% block content %}
<main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
    <div class="container py-1">
        <h1>Последние обновления на сайте</h1>
       {% for post in posts %}
    <ul>
        <li>
        Автор: {{ post.author.get_full_name }}
        </li>
        <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
    </ul>
    <p>{{ post.text }}</p>
    {% if post.group.slug %}
    <a href="{% url 'posts:group_list' post.group.slug%}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
        <!-- под последним постом нет линии -->
      </div>  
</main>
{% endblock %}